[helpers]

[default]
depends = []

[default.files]

[default.variables]


[sway.files]
sway = "~/.config/sway"
waybar = "~/.config/waybar"
rofi = "~/.config/rofi"
wallpapers = {target="~/wallpapers", type="symbolic"}

[sway.variables.sway]
wallpaper = "~/wallpapers/catppuccin.png"
battery = false
temperature = false
spotify = false

[neovim.files]
neovim = "~/.config/nvim"

[shell.files]
fish = "~/.config/fish"
"bash/env" = "~/.envrc"
"bash/rc" = "~/.bashrc"
"bash/profile" = "~/.bash_profile"



[mimeapps.files]
mimeapps = "~/.config/mimeapps.list"

